import { Injectable } from '@angular/core';

@Injectable()
export class CommonProvider {

  public teachesAtArray = [
    { value: '1', viewValue: 'Student\'s house' },
    { value: '2', viewValue: 'Academic institution' },
    { value: '3', viewValue: 'Both' }
  ];

  public genderArray = [
    { value: '1', viewValue: 'Male' },
    { value: '2', viewValue: 'Female' }
  ];

  public teachesInstitutionsArray = [
    { value: '1', viewValue: 'Holon Institute Of Technology' },
    { value: '2', viewValue: 'Technion' },
    { value: '3', viewValue: 'Tel-Aviv University' },
    { value: '4', viewValue: 'Ben Gurion University' },
    { value: '5', viewValue: 'Hebrew University' },
    { value: '6', viewValue: 'Bar-Ilan University' },
    { value: '7', viewValue: 'Weizmann Institute of Science' },
    { value: '8', viewValue: 'Ben-Gurion University of the Negev' },
    { value: '9', viewValue: 'Open University of Israel' },
    { value: '10', viewValue: 'Ariel University' },
    { value: '11', viewValue: 'Haredi College of Jerusalem' },
    { value: '12', viewValue: 'College of Law and Business' },
    { value: '13', viewValue: 'Academic College of Tel Aviv-Yafo' },
    { value: '14', viewValue: 'Afeka College of Engineering' },
    { value: '15', viewValue: 'Ashkelon Academic College' },
    { value: '16', viewValue: 'Beersheba Tehni School' },
    { value: '17', viewValue: 'Beit Zvi School of the Performing Arts' },
    { value: '18', viewValue: 'Bezalel Academy of Art and Design' },
    { value: '19', viewValue: 'Carmel Academic Center' },
    { value: '20', viewValue: 'Center for Academic Studies' },
    { value: '21', viewValue: 'COMAS' },
    { value: '22', viewValue: 'Dan Academic Center' },
    { value: '23', viewValue: 'Kfar-Avraham Technology College' },
    { value: '24', viewValue: 'Hadassah Academic College' },
    { value: '25', viewValue: 'Interdisciplinary Center Herzliya' },
    { value: '26', viewValue: 'Israel College of the Bible' },
    { value: '27', viewValue: 'Jerusalem Academy of Music and Dance' },
    { value: '28', viewValue: 'Jerusalem College of Engineering' },
    { value: '29', viewValue: 'Jerusalem College of Technology' },
    { value: '30', viewValue: 'Jerusalem University College' },
    { value: '31', viewValue: 'Kinneret Academic College' },
    { value: '32', viewValue: 'Lander Institute' },
    { value: '33', viewValue: 'Netanya Academic College' },
    { value: '34', viewValue: 'Ono Academi College' },
    { value: '35', viewValue: 'ORT Braude College of Engineering' },
    { value: '36', viewValue: 'Peres Academic Center' },
    { value: '37', viewValue: 'Reidman College' },
    { value: '38', viewValue: 'Ruppin Academic Center' },
    { value: '39', viewValue: 'Sapir Academic College' },
    { value: '40', viewValue: 'Sami Shamoon College of Engineering' },
    { value: '41', viewValue: 'Shenkar College of Engineering and Design' },
    { value: '42', viewValue: 'Tel-Hai Academic College' },
  ];

  public subjectsArray = [
    { value: '1', viewValue: 'Programming in C' },
    { value: '2', viewValue: 'Introduction to Computer Science' },
    { value: '3', viewValue: 'Data Structures' },
    { value: '4', viewValue: 'Mathematical Tools for Computer Science' },
    { value: '5', viewValue: 'Advanced Programming Workshop' },
    { value: '6', viewValue: 'Computer Organization and Assembly' },
    { value: '7', viewValue: 'Computer Structure and Switching Theory' },
    { value: '8', viewValue: 'Operating Systems' },
    { value: '9', viewValue: 'Automata and Formal Languages' },
    { value: '10', viewValue: 'Design and Analysis of Algorithms' },
    { value: '11', viewValue: 'Logic For Computer Science' },
    { value: '12', viewValue: 'Logic Programming' },
    { value: '13', viewValue: 'Data Base Systems' },
    { value: '14', viewValue: 'Compilation Theory' },
    { value: '15', viewValue: 'Computer Communication Networks' },
    { value: '16', viewValue: 'Computability and Complexity of Algorithms' },
    { value: '17', viewValue: 'Object Oriented Programming' },
    { value: '18', viewValue: 'Foundations of Information Systems' },
    { value: '19', viewValue: 'Graph Theory' },
    { value: '20', viewValue: 'Real Time Systems' },
    { value: '21', viewValue: 'System Programming' },
    { value: '22', viewValue: 'Design Patterns' },
    { value: '23', viewValue: 'Data Mining' },
    { value: '24', viewValue: 'Computer Vision' },
    { value: '25', viewValue: 'Geometry View Multiple' },
    { value: '26', viewValue: 'Computer Graphics' },
    { value: '27', viewValue: 'Introduction to Fuzzy Logic' },
    { value: '28', viewValue: 'Introduction to Cryptography' },
    { value: '29', viewValue: 'Data Compression' },
    { value: '30', viewValue: 'Signal and Image Processing ' },
    { value: '31', viewValue: 'Computer Architecture' },
    { value: '32', viewValue: 'Hardware Description Languages' },
    { value: '33', viewValue: 'Digital Systems' },
    { value: '34', viewValue: 'Expert Systems' },
    { value: '35', viewValue: 'Artificial Intelligence' },
    { value: '36', viewValue: 'Programming in C#' },
    { value: '37', viewValue: 'Programming in Java' },
    { value: '38', viewValue: 'Programming in Python' },
    { value: '39', viewValue: 'Programming in JavaScript' },
    { value: '40', viewValue: 'Numerical Analysis' },
    { value: '41', viewValue: 'Numerical algorithms' },
    { value: '42', viewValue: 'Logic Design' },
    { value: '43', viewValue: 'Approximation algorithms' },
    { value: '44', viewValue: 'Secure Quality Programs' },
    { value: '45', viewValue: 'Introduction to Robotics' },
    { value: '46', viewValue: 'Semiconductors' },
    { value: '47', viewValue: 'Electrical Engineering Laboratory' },
    { value: '48', viewValue: 'Semiconductor Devices' },
    { value: '49', viewValue: 'Switching and Logic Design' },
    { value: '50', viewValue: 'Introduction to Linear Systems' },
    { value: '51', viewValue: 'Analog Linear Electronic Circuits' },
    { value: '52', viewValue: 'Energy Conversion' },
    { value: '53', viewValue: 'Signals and Systems' },
    { value: '54', viewValue: 'Electromagnetic Fields' },
    { value: '55', viewValue: 'Digital Circuits' },
    { value: '56', viewValue: 'Introduction to Control Theory' },
    { value: '57', viewValue: 'Laboratory of Logic Digital Circuits' },
    { value: '58', viewValue: 'Communication Engineering' },
    { value: '59', viewValue: 'Electric Drives' },
    { value: '60', viewValue: 'Microprocessors' },
    { value: '61', viewValue: 'Introduction to Microwaves' },
    { value: '62', viewValue: 'Microprocessors Laboratory' },
    { value: '63', viewValue: 'Waves Propagation' },
    { value: '64', viewValue: 'Photonics and Electro-optics systems' },
    { value: '65', viewValue: 'Antennas and Radiation' },
    { value: '66', viewValue: 'Power Systems' },
    { value: '67', viewValue: 'Waves and Distributed Systems' },
    { value: '68', viewValue: 'Conversion Laboratory Energy' },
    { value: '69', viewValue: 'Filter Design' },
    { value: '70', viewValue: 'Power Electronics Systems' },
    { value: '71', viewValue: 'Advanced Control Theory' },
    { value: '72', viewValue: 'High Voltage Engineering' },
    { value: '73', viewValue: 'Digital Signal Processing' },
    { value: '74', viewValue: 'Electronics Computer Aided Design' },
    { value: '75', viewValue: 'Random Signals' },
    { value: '76', viewValue: 'Network Theory' },
    { value: '77', viewValue: 'Neural Networks' },
    { value: '78', viewValue: 'Dynamics and Control Spacecraft' },
    { value: '79', viewValue: 'Modern Optics and Electro optics' },
    { value: '80', viewValue: 'Engineering Economics' },
    { value: '81', viewValue: 'Introduction to Lasers' },
    { value: '82', viewValue: 'Electronic Materials' },
    { value: '83', viewValue: 'Robots Dynamics and Control' },
    { value: '84', viewValue: 'High and Low Voltages Devices' },
    { value: '85', viewValue: 'Receiving and Transmitting Techniques' },
    { value: '86', viewValue: 'Statistics and Probability' },
    { value: '87', viewValue: 'Linear Algebra' },
    { value: '88', viewValue: 'Calculus' },
    { value: '89', viewValue: 'Discrete Mathematics' },
    { value: '90', viewValue: 'Ordinary Differential Equations' },
    { value: '91', viewValue: 'Mathematical Modeling' },
    { value: '92', viewValue: 'Partial Differential Equations' },
    { value: '93', viewValue: 'Complex Valued Functions' },
    { value: '94', viewValue: 'Fourier Series and Integral Transforms' },
    { value: '95', viewValue: 'Introduction to Modern Analysis' },
    { value: '96', viewValue: 'Algorithm in Optimization' },
    { value: '97', viewValue: 'Machine Learning' },
    { value: '98', viewValue: 'Complex Functions' },
    { value: '99', viewValue: 'Statistical Inference' },
    { value: '100', viewValue: 'Machine Vision' },
    { value: '101', viewValue: 'Forecasting Methods' },
    { value: '102', viewValue: 'Fluid Mechanics' },
    { value: '103', viewValue: 'Mechanics of Solids' },
    { value: '104', viewValue: 'Web Programming' },
  ];

  public reasonToContactArray = [
    { value: 'Suggestion', viewValue: 'Suggestion' },
    { value: 'Investment', viewValue: 'Investment' },
    { value: 'Careers', viewValue: 'Careers' },
    { value: 'Complain', viewValue: 'Complain' },
    { value: 'Bug report', viewValue: 'Bug report' },
    { value: 'Other', viewValue: 'Other' }
  ];

  constructor() {
  }
}
